### ISSUE TITLE
Installing Steam create wrong Steam icon and name

### ISSUE THREAD

**Issue by deathxxx123** [pop-os/steam#14] opened 2024-02-14 09:44 UTC
On pop-shop or in terminal i try install, reinstall, purge steam but always i got wrong icon with name "install steam"
But installing Steam from steam site is ok. I got right icon and with name "Steam"

**Comment by leviport** [comment] 2024-02-14 15:14
Duplicate of https://github.com/pop-os/steam/issues/13

**Closed by leviport** 2024-02-14 15:14 UTC
